WebApplication_FirstAspNetCoreApp/Models/ErrorViewModel.cs
namespace WebApplication_FirstAspNetCoreApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication_FirstAspNetCoreApp/Models/Student.cs
namespace WebApplication_FirstAspNetCoreApp.Models
{
	public class Student
	{
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public int Age { get; set; }
		public bool YeniKayitMi { get; set;}
		public string Password { get; set; }
	}
}

WebApplication_FirstAspNetCoreApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication_FirstAspNetCoreApp.Controllers
{
    public class AccountController : Controller
    {
        //Account/Login
        public IActionResult Login()
        {
            return View();
        }
        //Account/Register
        public IActionResult Register()
        {
            return View();
        }
    }
}

WebApplication_FirstAspNetCoreApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication_FirstAspNetCoreApp.Models;

namespace WebApplication_FirstAspNetCoreApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication_FirstAspNetCoreApp/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication_FirstAspNetCoreApp.Models;

namespace WebApplication_FirstAspNetCoreApp.Controllers
{
	public class StudentController : Controller
	{
		public IActionResult Details()
		{
			Student student = new Student
			{
				FirstName = "John",
				LastName = "Smith",
				Age = 22,
				Password = "12345",
				YeniKayitMi = true
			};

			return View(student);
		}
	}
}

WebApplication_FirstAspNetCoreApp/Controllers/WhatIsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication_FirstAspNetCoreApp.Models;

namespace WebApplication_FirstAspNetCoreApp.Controllers
{
    public class WhatIsController : Controller
    {
        public IActionResult RazorSyntax()
        {
            return View();
        }
		public IActionResult HtmlHelpers()
		{
            Student student = new Student { FirstName="Tolga" };

			return View(student);
		}
	}
}

WebApplication_FirstAspNetCoreApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication_FirstAspNetCoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication_FirstAspNetCoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication_FirstAspNetCoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication_FirstAspNetCoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
	                    </li>
	                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WhatIs" asp-action="RazorSyntax">RazorSyntax</a>
	                    </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WhatIs" asp-action="HtmlHelpers">HtmlHelpers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication_FirstAspNetCoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication_FirstAspNetCoreApp/Views/Student/Details.cshtml
@using System.Diagnostics.Tracing
@model Student

<h1>Student Details</h1>
<hr />

<div>
	<div>Adi: @Model.FirstName</div>
	<div>Soyadi: @Model.LastName</div>
	<div>Yas: @Model.Age</div>
	<div>
		Yeni kayıt mı: @((Model.YeniKayitMi) ? "Evet" : "Hayır")
	</div>
	<div>Şifresi: @Model.Password</div>
</div>

WebApplication_FirstAspNetCoreApp/Views/WhatIs/HtmlHelpers.cshtml
@model Student

<h1>HTML Helpers</h1>
<hr />

<div>
	<div>
		@Html.ActionLink("Ana sayfaya git", "Index", "Home", null, new { @class="btn btn-primary"})
	</div>
	<div>
		@Html.Raw("<b>Bu metin onemlidir</b>")
	</div>
	<div>
		@*<input type="text" placeholder="adınız" value="John" />*@
		@Html.TextBox("name", null, new { placeholder="adinizi yaziniz", @class="form-control" })
		@Html.TextBoxFor(m => m.FirstName, new { placeholder="ogrenci adini yaziniz", @class="form-control" } )
	</div>
	<div>
		@Html.TextArea("Aciklama", "buraya aciklama giriniz", new {@class="form-control", rows="4"})
	</div>
	<div>
		@Html.CheckBox("secim", true)
	</div>
	<div>
		@Html.RadioButton("renk", null, true)
		@Html.RadioButton("renk", null, false)
		@Html.RadioButton("renk", null, false)
	</div>
	<div>
		@{
			var droppedDownList = new List<SelectListItem> {
				new SelectListItem("Mavi", "Blue"),
				new SelectListItem("Yesil", "Green"),
				new SelectListItem("Kirmizi", "Red"),
			};
		}

		@Html.DropDownList("renkler", droppedDownList, "Seciniz", new { @class="form-control"})
	</div>
	<div>
		@Html.ListBox("renkler2", droppedDownList, new { @class="form-control"})
	</div>
	<div>
		@Html.Password("sifre", "123456", new { @class="form-control"})
	</div>
	<div>
		@Html.Label("etiket", "Adınız")
		@Html.TextBox("txtName", null, new {@class="form-control"})
	</div>
	<div>
		@Html.Display("FirstName")
	</div>
	<div>
		@Html.Hidden("gizli", "bu gizli veridir.")
	</div>
</div>

WebApplication_FirstAspNetCoreApp/Views/WhatIs/RazorSyntax.cshtml
<h1>Razor Syntax</h1>
<hr/>

<div>(Inline Expression) Tarih: @DateTime.Now.ToString()</div>

<br />
@{
	//Multi-Statement Code Block
	string date = DateTime.Now.ToShortDateString();
	string message = "Merhaba ASPNET MVC Core";
}

<div>
	<h5>Multi-Statement Code Block</h5>
	<div>Bugünün tarihi: @date</div>
	<div>Mesaj: @message</div>
</div>
<br />

<div>
	<h5>Display Text from Code Block</h5>
	<div>
		@{
			string date2 = DateTime.Now.ToShortDateString();
			string message2 = "Hello, world";

			<text>Mesajım: </text> @message2 <br />
			@:Mesajım şudur: @message2 <br />
			@:Tarih: @date2
		}
	</div>
</div>
<br />
<div>
	<h5>If-Else Condition</h5>
	@if (DateTime.IsLeapYear(DateTime.Now.Year))
	{
		@DateTime.Now.Year @:yılı bir artık yıldır.
	}
	else
	{
		@DateTime.Now.Year @:yılı bir artık yıl değildir.
	}
</div>
<br />
<div>
	<h5>Loops</h5>
	@for (int i = 0; i < 10; i++)
	{
		<li>Item @(i+1)</li>
	}
</div>
<br />